services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../src/stores/ChromaDB:/app/stores/ChromaDB
      - ../src/stores/ChatHistory:/app/stores/ChatHistory
      - ../src/output:/app/output
    env_file:
      - ../src/.env
    restart: unless-stopped
